<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>POST</name>
   <tag></tag>
   <elementGuidId>f039c1f7-756e-44c2-8553-e4ac557d6560</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>true</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <katalonVersion>10.1.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path>/api/ShoppingCart/AddToCart/{userId}/{bookId}</path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>//api/ShoppingCart/AddToCart/${userId}/${bookId}</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>null</defaultValue>
      <description>&lt;integer> {Required} null</description>
      <id>e42702dc-170d-4240-941f-4dfde8269f8a</id>
      <masked>false</masked>
      <name>userId</name>
   </variables>
   <variables>
      <defaultValue>null</defaultValue>
      <description>&lt;integer> {Required} null</description>
      <id>14f022f3-6560-43c5-b2df-cfe9be57d0ce</id>
      <masked>false</masked>
      <name>bookId</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
