<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>GET</name>
   <tag></tag>
   <elementGuidId>e6997358-7e21-4359-a94d-13e5b869e511</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>true</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <katalonVersion>10.1.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path>/api/ShoppingCart/SetShoppingCart/{oldUserId}/{newUserId}</path>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>//api/ShoppingCart/SetShoppingCart/${oldUserId}/${newUserId}</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>null</defaultValue>
      <description>&lt;integer> {Required} null</description>
      <id>d1fa53f0-f1f9-4987-abfc-2b7c817601b5</id>
      <masked>false</masked>
      <name>oldUserId</name>
   </variables>
   <variables>
      <defaultValue>null</defaultValue>
      <description>&lt;integer> {Required} null</description>
      <id>6de5099e-6ad2-44c3-abbd-c9f09d10d20d</id>
      <masked>false</masked>
      <name>newUserId</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
